### ISSUE TITLE
[To do] Geospatial data - Test the layer loading time

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#29]
After V1 is implemented, test the loading time of the layers to ensure it is acceptable.

**Comment by EmilieVrot** [comment]
I discussed this to our technical team and they suggest to make a "pyramide cache": generate caches of all zoom servers so that the QGIS server no longer needs to recalculate them

Is it something that you plan to put in place? Or do you have other ideas?

**Comment by EmilieVrot** [comment]
Can you also add a loading icon when the layers take time to be displayed? Thanks

**Comment by carlabiscotti** [comment]
Emilie, I'm assessing this with more detail now. I don't feel the layers load slowly. Could you please point out to which specific layers you refer to?

Please find in[ this link](https://drive.google.com/file/d/1kApEihhJke0NRK0p_eotIBWK4pko4Qim/view?usp=sharing) a screen recording of how this is working for me so that we have a common reference.

**Comment by EmilieVrot** [comment]
This one is for sprint 8, I think we can discuss it later when all the layers will be implemented. Still, some users might have bad Internet connection and this loading icon might be relevant.

**Comment by carlabiscotti** [comment]
Hi Emilie, yes we can discuss it later. At that point we should clarify what issue we are trying to solve: performance issues, issues due to bad internet connection of users, others.

**Comment by EmilieVrot** [comment]
I'll close this issue since we haven't encountered any issues with layer loading times. We'll reopen it if necessary.
